site_name: orbit-tessellation
repo_url: https://github.com/ilikecubesnstuff/orbit-tessellation/

theme:
  name: readthedocs

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings

nav:
- Home: index.md
- Code Reference: reference/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
