site_name: Orbit Tessellation in Python
repo_url: https://github.com/ilikecubesnstuff/orbit-tessellation/

theme:
  name: 'material'
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
  # Adapted from https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Atkinson Hyperlegible
    code: Ubuntu Mono
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate  # NOTE: undecided, can be unwieldy

plugins:
- search:
    lang: en
    # taken from https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#+search.separator
    separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings

nav:
- Home: index.md
- About:
  - about/index.md
  - about/installation.md
  - about/motivation.md
  - about/algorithm.md
  - Usage: about/usage.md
- User Guide:
  - user/index.md
  - user/introduction.md
  - Tutorials:
    - user/tutorials/agama_examples.md
    - user/tutorials/gala_examples.md
    - user/tutorials/galpy_examples.md
- Developer Guide:
  - dev/index.md
  - dev/contributing.md
- API Reference: reference/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

extra_css:
  - stylesheets/extra.css
