[project]
name = "tessellation"
version = "0.1.0"
description = "A Python package for evaluating orbit commensurability using Delaunay tessellation."
authors = [
    {name = "ilikecubesnstuff", email = "subho1618@gmail.com"},
]
dependencies = [
    "numpy>=1.24.4",
    "scipy>=1.9.3",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
