[project]
name = "tessellation"
version = "0.1.0"
description = "A Python package for evaluating orbit commensurability using Delaunay tessellation."
authors = [
    {name = "ilikecubesnstuff", email = "subho1618@gmail.com"},
]
dependencies = [
    "numpy>=1.24.4",
    "scipy>=1.9.3",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
plotting = [
    "matplotlib>=3.7.2",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.2",
]
dev = [
    "tox-pdm>=0.7.0",
]
