# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Package Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.8"
    - name: Install package
      run: |
        pdm install

    - name: Publish to TestPyPI
      env:
        PDM_PUBLISH_USERNAME: __token__
        PDM_PUBLISH_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        pdm publish --repository testpypi

    - name: Test install from TestPyPI
      run: |
        pip install --index-url https://test.pypi.org/simple/ orbit-tessellation

    - name: Publish to PyPI
      env:
        PDM_PUBLISH_USERNAME: __token__
        PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pdm publish
